spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  config:
    import: datasource.yml

logging:
  level:
    org.hibernate.SQL: debug
